### PR TITLE
ci(validate): all well-formed, validate changed

### PR DESCRIPTION
**Pull request by line-o**
no file change detected:
https://github.com/BetaMasaheft/Narrative/runs/7939242413

Screenshot 2022-08-21 at 15 48 16

changed file, validation successful:
https://github.com/BetaMasaheft/Narrative/runs/7939252216

Screenshot 2022-08-21 at 15 49 49

failed validation of 1 deliberately broken file:
https://github.com/BetaMasaheft/Narrative/runs/2898679564

Screenshot 2022-08-21 at 15 50 39

### CODE REVIEW

**Comment by line-o** [comment]
@duncdrum This needs cleanup. I want to discuss the changes and how to proceed.

**Comment by line-o** [comment]
@duncdrum This PR is now ready to be merged to master. This will also let us see if the push workflow does what it should.

**Comment by line-o** [comment]
@eu-genia This is the very first implementation for the updated workflow we discussed.

**Comment by eu-genia** [comment]
thank you, am looking forward to testing it out

**Comment by line-o** [comment]
For testing and documentation purposes the last commit changes one file (removing a blank line).

**Review by duncdrum — APPROVED** [review]

**Pull request merged**
