### PR TITLE
new IDs for a few commemorations

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Comment by thea-m** [comment]
....and NAR0186SenMaryDeath stayed in the wrong folder :( not my day apparently

**Comment by eu-genia** [comment]
you can still move it, there has been no commit yet

**Comment by eu-genia** [comment]
no commit to master i mean

**Comment by thea-m** [comment]
Thank you! I hope that now that I have it written somewhere I will at least remember to look it up!

**Review by CarstenHoffmannMarburg — APPROVED** [review]

**Review by eu-genia — APPROVED** [review]

**Pull request merged**
